const AssetPhasesEnum = Object.freeze({
  INITIATIONREQUEST: 1,
  INITIATIONAPPROVAL: 5,
  INITIATIONACOMPLETE: 2,
  INITIATIONAPPROVALAPROCEED: 6,
  EVALUATIONCHANGE: 3,
  EVALUATIONAPPROVAL: 5,
  IMPLEMENTATIONAPPROVAL: 4,
  IMPTRANS:13,
  INITRANS:12
});

export default AssetPhasesEnum;
